# Makefile for main src

# Default target: build program helloworld
#all: test_factorial
all: helloworld

# The program helloworld must link with the object file factorial.o
#test_factorial: factorial.o
helloworld: factorial.o

# To clean, remove all object files
clean:
	rm -f *.o 
