# Makefile for main src

# Default target: build program helloworld
#all: helloworld
all: test_factorial

# The program helloworld must link with the object file factorial.o
#helloworld: factorial.o
test_factorial: factorial.o

# To clean, remove all object files
clean:
	rm -f *.o 
